/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
/*
Ext.Loader.setPath({
    'Gnt.model.Task' : 'resources/gantt/gntPlugin.js'
});*/

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'PartNumberModel',
        'NetworkModel',
        'ControlPointModel',
        'IntegrationPointModel',
        'ModelUnitModel',
        'UserModel',
        //'LineModel',
        'SelectionVariantModel',
        'ColumnVariantModel',
        'SelectedObjectModel',
        'VersionModel',
        'SearchModel',
        'ResultsModel',
        'FieldsModel',
        'GanttConfigModel',
        'PassedObjectsModel'
    ],
    stores: [
        'UserStoreXml',
        'PartNumberStoreXml',
        'NetworkStoreXml',
        'ControlPointStoreXml',
        'IntegrationPointStoreXml',
        'ModelUnitStoreXml',
        'SelectionVariantStoreXml',
        'ColumnVariantStoreXml',
        'SelectedObjectStoreXml',
        'VersionStoreXml',
        'PlantStoreXml',
        'ProgramStoreXml',
        'PrimaryMissionStoreXml',
        'BuildItemStoreXml',
        'TailNumberStoreXml',
        'EffectivityStoreXml',
        'NameStoreXml',
        'NotesStoreXml',
        'SearchStoreXml',
        'ResultsStoreXml',
        'FieldStoreXml',
        'GanttConfigStoreXml',
        'SortByStore',
        'PassedObjectsStoreXml',
        'PassedObjectStoreXml2',
        'ColumnVariantStore2Xml',
        'VariantTypeStore',
        'ColumnStoreXml',
        'GanttViewStore',
        'PassedConfigStoreXml',
        'SummaryOptionsStore2',
        'ParamStoreXml',
        'YesNoStore',
        'BaselineOptionsStore',
        'InternalStore'
    ],
    views: [
        'MainViewport',
        'EventTrigger',
        'MyPanel12'
    ],
    controllers: [
        'Main'
    ],
    name: 'MyApp',
    launch: function() {
        Ext.create('MyApp.view.MainViewport');
    }

});

